name: set

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ 'gotip' ]
    name: Go install
    steps:
      - uses: actions/checkout@v2
      - name: Setup gotip
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "::set-env name=GOROOT::$HOME/gotip"
          echo "::add-path::$HOME/gotip/bin"
      - name: unit-test
        run: |
         go test -v ./...
