name: "UnitTest"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'go1.18beta1' ]
    name: Go install
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0-beta1'
      - run: |
          go version
          go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
